-- ==============================================================================
-- ShopHub Supabase Schema Migration: User-Specific Cart & RLS Policies
-- Run this script in the Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. Create or Update Cart Table
CREATE TABLE IF NOT EXISTS public.cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  product_id TEXT NOT NULL,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  count INT NOT NULL DEFAULT 1,
  product_data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT cart_user_product_key UNIQUE (user_id, product_id)
);

-- 2. Alter Table Migrations (in case table was previously created with partial columns)
ALTER TABLE public.cart ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.cart ADD COLUMN IF NOT EXISTS product_id TEXT;
ALTER TABLE public.cart ADD COLUMN IF NOT EXISTS quantity INT DEFAULT 1;
ALTER TABLE public.cart ADD COLUMN IF NOT EXISTS count INT DEFAULT 1;
ALTER TABLE public.cart ADD COLUMN IF NOT EXISTS product_data JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.cart ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- Add unique constraint for (user_id, product_id) if not already present
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'cart_user_product_key'
  ) THEN
    BEGIN
      ALTER TABLE public.cart ADD CONSTRAINT cart_user_product_key UNIQUE (user_id, product_id);
    EXCEPTION WHEN duplicate_table OR duplicate_object THEN
      NULL;
    END;
  END IF;
END $$;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.cart ENABLE ROW LEVEL SECURITY;

-- 4. Clean up any existing policies
DROP POLICY IF EXISTS "Users can view their own cart items" ON public.cart;
DROP POLICY IF EXISTS "Users can insert their own cart items" ON public.cart;
DROP POLICY IF EXISTS "Users can update their own cart items" ON public.cart;
DROP POLICY IF EXISTS "Users can delete their own cart items" ON public.cart;

-- 5. Row Level Security Policies
-- Users (and Admins) can ONLY read their own cart items
CREATE POLICY "Users can view their own cart items" 
  ON public.cart FOR SELECT 
  TO authenticated 
  USING (auth.uid() = user_id);

-- Users (and Admins) can ONLY insert items for their own user_id
CREATE POLICY "Users can insert their own cart items" 
  ON public.cart FOR INSERT 
  TO authenticated 
  WITH CHECK (auth.uid() = user_id);

-- Users (and Admins) can ONLY update their own cart items
CREATE POLICY "Users can update their own cart items" 
  ON public.cart FOR UPDATE 
  TO authenticated 
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users (and Admins) can ONLY delete their own cart items
CREATE POLICY "Users can delete their own cart items" 
  ON public.cart FOR DELETE 
  TO authenticated 
  USING (auth.uid() = user_id);
