-- ==============================================================================
-- ShopHub Supabase Schema Migration: User-Specific Wishlist & RLS Policies
-- Run this script in the Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. Create or Update Wishlist Table
CREATE TABLE IF NOT EXISTS public.wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  product_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT wishlist_user_product_key UNIQUE (user_id, product_id)
);

-- 2. Alter Table Migrations (in case table was previously created with partial columns)
ALTER TABLE public.wishlist ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.wishlist ADD COLUMN IF NOT EXISTS product_id TEXT;
ALTER TABLE public.wishlist ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- Add unique constraint for (user_id, product_id) if not already present
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'wishlist_user_product_key'
  ) THEN
    BEGIN
      ALTER TABLE public.wishlist ADD CONSTRAINT wishlist_user_product_key UNIQUE (user_id, product_id);
    EXCEPTION WHEN duplicate_table OR duplicate_object THEN
      NULL;
    END;
  END IF;
END $$;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

-- 4. Clean up any existing policies
DROP POLICY IF EXISTS "Users can view their own wishlist items" ON public.wishlist;
DROP POLICY IF EXISTS "Users can insert their own wishlist items" ON public.wishlist;
DROP POLICY IF EXISTS "Users can delete their own wishlist items" ON public.wishlist;

-- 5. Row Level Security Policies
-- Users can ONLY read their own wishlist items
CREATE POLICY "Users can view their own wishlist items" 
  ON public.wishlist FOR SELECT 
  TO authenticated 
  USING (auth.uid() = user_id);

-- Users can ONLY insert items for their own user_id
CREATE POLICY "Users can insert their own wishlist items" 
  ON public.wishlist FOR INSERT 
  TO authenticated 
  WITH CHECK (auth.uid() = user_id);

-- Users can ONLY delete their own wishlist items
CREATE POLICY "Users can delete their own wishlist items" 
  ON public.wishlist FOR DELETE 
  TO authenticated 
  USING (auth.uid() = user_id);
